# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed62ca728168f0a2925c8f939d1289bb7f378aa3c9a4c6aac5036ff6f138474f357cd1e508ef065b1948cd84a7df7d27dc437dab90e017b8c1b563a57cca0262

test:
  secret_key_base: 7179e557e8477f02f9c4d8391686c23d43cd6aa371a4b30f5fad4cf5eb3d268ee588eff08becbf27c0a579003edb301c0f5a3906aa7ddc76d3a9bbbe885c548a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
